### ISSUE TITLE
TwoCamControl timed out warning

### ISSUE THREAD

**Issue by martinhgregory** [nod5/TwoCamControl#8]
I have sucessfully installed and used TwoCamControl but after a few minutes of use and taking around 20 shots on both cameras, I get the message:

WARNING: timed outWARNING: timed out waiting for shot script 
- ERROR: uninit a script is already running
- con 5> path D:/Users/20190225195212/0023R
- ERROR: unknown command 'path'

on both camera windows

My setup details are:
Your camera model, 2 x Canon IXUS 90IS  running ver 1.00D
the version of CHDK: 1.4.1 rev 5154 Jan 13, 2019
chdkptp: ver 21 (I think)
TwoCamControl: version 2018-11-13
Windows version: 10 Home ver 1803
language: English UK

I've tried setting CHDK settings Disable LCD Off to ALWAYS and the camera to power saving OFF in the hope of fixing this but neither help.

How do I sort out this issue?

Martin

**Comment by nod5** [comment]
Thank you for the detailed report. 

I think this is an issue with the CHDK firmware and/or chdkptp rather than TwoCamControl.

[This page](https://chdk.setepontos.com/index.php?topic=13377.0) in the CHDK forum mentions the same error `WARNING: timed out waiting for shot scripts`.

Try reposting your issue text in the CHDK forum [chdkptp thread](https://chdk.setepontos.com/index.php?topic=6231.0).  
Add the information that the problem happens when shooting with chdkptp in `rsint` mode.

You can also test if using the latest developer version of the CHDK firmware makes a difference
http://mighty-hoernsche.de/trunk/

Worth noting: if the unwanted timeout occurs only when the user waits a minute or more between each Shoot command then the solution is to increase the cmdwait parameter in rsint options on TwoCamControl's [Setup tab](https://github.com/nod5/TwoCamControl#optional-settings-default-value). But you didn't mention waiting a long time between commands so that is probably not it in this case.

**Comment by nod5** [comment]
Closed since not actionable.
